
target 'OneWaySynchronizerDemo' do
  use_frameworks!
  
  pod 'OneWaySynchronizer', :path => './..'
  pod 'Alamofire'
  
  # Pods for OneWaySynchronizerDemo
  
  target 'OneWaySynchronizerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
